# Generated by Django 5.2.7 on 2026-01-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_respiracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cazadores',
            name='imagen_cazador',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='imagenes/'),
        ),
    ]
