# Generated by Django 5.2.7 on 2026-01-22 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cazadores_imagen_cazador'),
    ]

    operations = [
        migrations.AddField(
            model_name='respiracion',
            name='imagen',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='imagenes/respiraciones/'),
        ),
        migrations.AddField(
            model_name='respiracion',
            name='usuarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respiraciones', to='app.cazadores'),
        ),
    ]
