# Generated by Django 5.2.7 on 2026-01-24 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_respiracion_imagen_respiracion_usuarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respiracion',
            options={'verbose_name': 'Respiración', 'verbose_name_plural': 'Respiraciones'},
        ),
        migrations.RemoveField(
            model_name='respiracion',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='respiracion',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='respiracion',
            name='modificado',
        ),
        migrations.RemoveField(
            model_name='respiracion',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='respiracion',
            name='color_catana',
            field=models.CharField(blank=True, help_text='Color que toma la Nichirin', max_length=50),
        ),
        migrations.AddField(
            model_name='respiracion',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estilos_creados', to='app.cazadores'),
        ),
        migrations.AddField(
            model_name='respiracion',
            name='derivada_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivaciones', to='app.respiracion'),
        ),
        migrations.AddField(
            model_name='respiracion',
            name='imagen_representativa',
            field=models.ImageField(blank=True, null=True, upload_to='respiraciones/'),
        ),
        migrations.AlterField(
            model_name='respiracion',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Postura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Ej: Primera postura, Segunda postura...')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen_accion', models.ImageField(blank=True, null=True, upload_to='posturas/')),
                ('creador_especifico', models.ForeignKey(blank=True, help_text='Llenar solo si esta postura es exclusiva de un usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cazadores')),
                ('respiracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posturas', to='app.respiracion')),
            ],
            options={
                'verbose_name': 'Postura',
                'verbose_name_plural': 'Posturas',
                'ordering': ['numero'],
                'unique_together': {('respiracion', 'numero')},
            },
        ),
    ]
