# Generated by Django 5.2.7 on 2026-01-24 22:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_respiracion_options_remove_respiracion_creado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postura',
            name='creador_especifico',
        ),
        migrations.RemoveField(
            model_name='respiracion',
            name='creador',
        ),
        migrations.AddField(
            model_name='cazadores',
            name='respiraciones',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='app.respiracion'),
        ),
        migrations.AddField(
            model_name='postura',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postura',
            name='creador_de_postura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posturas_propias', to='app.cazadores'),
        ),
        migrations.AddField(
            model_name='postura',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='respiracion',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respiracion',
            name='creador_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estilos_originados', to='app.cazadores'),
        ),
        migrations.AddField(
            model_name='respiracion',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postura',
            name='numero',
            field=models.PositiveIntegerField(help_text='Ej: 1, 2, 3...'),
        ),
        migrations.AlterField(
            model_name='respiracion',
            name='color_catana',
            field=models.CharField(blank=True, help_text='Color de la Nichirin', max_length=50),
        ),
    ]
